tr181: Add missing symbols for openwrt builds
Fixes these linker errors when building with --generic-openwrt

/usr/bin/ld: /usr/local/lib/libbbfdm.so: undefined reference to `os_get_supported_modes'
/usr/bin/ld: /usr/local/lib/libbbfdm.so: undefined reference to `os_set_QoSClassification_DestVendorClassID'
/usr/bin/ld: /usr/local/lib/libbbfdm.so: undefined reference to `os_get_QoSClassification_DestVendorClassID

Signed-off-by: Daniel Danzberger <daniel@dd-wrt.com>